name: Deploy Med-Queue ke EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy ke EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Masuk ke folder project
            cd /home/ubuntu/Med-Queue || exit

            # 2. Paksa Git untuk sinkron dengan GitHub (Hapus konflik lokal)
            sudo git fetch --all
            sudo git reset --hard origin/main
            sudo git clean -fd

            # 3. Update file .env dari GitHub Secrets
            cat > .env << EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            DB_NAME=${{ secrets.DB_NAME }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            PORT=3000
            EOF

            # 4. Bersihkan proses dan container lama
            sudo fuser -k 3000/tcp || true
            sudo docker stop Med-Queue-app || true
            sudo docker rm Med-Queue-app || true
            sudo docker system prune -f

            # 5. Build dan jalankan ulang
            sudo docker build -t med-queue-img .
            sudo docker run -d \
              --name Med-Queue-app \
              --restart always \
              -p 3000:3000 \
              --env-file .env \
              med-queue-img

            echo "✅ Deploy Berhasil dan Port 3000 Segar Kembali!"